### ISSUE TITLE
can not convert image in v2.2.5

### ISSUE THREAD

**Issue by xhxhxhxh** [CatHood0/flutter_quill_to_pdf#17]
if my local image path contains ".", like ".jpg", `static final RegExp IMAGE_LOCAL_STORAGE_PATH_PATTERN =
      RegExp(r'^((\/[a-zA-Z0-9-_]+)+|\/)$');` will return false, finally throw an error.

**Comment by CatHood0** [comment]
I'll take a look about it. Thanks for reporting this error!
